version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: padelit
    container_name: padelit_application
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    volumes:
      - ./Database/sql:/var/lib/msdb
